name: monitoring
description: A Flutter project for monitoring temperature

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.10 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
